### ISSUE TITLE
generated schematics have missing part reference

### ISSUE THREAD

**Issue by asomers** [werner2101/spicelib#1]
All of the generated schematics in model_tests/VENDOR/SECTION/\* have an unresolved reference to the part under test.  If you open it up in gschem, it shows a 'Component Not Found' error message.  Also, the spice netlists have no reference to the component under test.

I have tested this in spicelib-0.0.2, spicelib-0.0.3, and the git head as of september 21.

**Comment by asomers** [comment]
Here is an example of the generated schematic on my system:
model_tests/nxp/diodes/BAS116H_NXP01004/dc_current.sch

v 20070818 1
C 40000 40000 0 0 0 title-B.sym
N 47200 46400 49300 46400 4
C 48900 47800 1 270 0 BAS116H_NXP01004
{
T 49600 47350 5 10 1 1 0 0 1
refdes=D1
}
C 46900 46800 1 0 0 idc-1.sym
{
T 47600 47450 5 10 1 1 0 0 1
refdes=I1
T 47600 47650 5 10 0 0 0 0 1
device=CURRENT_SOURCE
T 47600 47850 5 10 0 0 0 0 1
footprint=none
T 47600 47250 5 10 1 1 0 0 1
value=DC 1mA
}
N 47200 46400 47200 46800 4
N 47200 48000 47200 48200 4
N 47200 48200 49300 48200 4
{
T 49000 48300 5 10 1 1 0 0 1
netname=in
}
N 49300 47800 49300 48200 4
N 49300 46400 49300 46900 4
C 48200 46100 1 0 0 gnd-1.sym

**Comment by bert** [comment]
Hi,
Did you add the model_tests/VENDOR/SECTION/\* directories to the gschem library search path.
Kind regards,
Bert Timmerman.

**Comment by werner2101** [comment]
Hi Alan,

have you connected the gedaparts system to gschem?
The test circuit looks fine and complete.

You have to copy the geda-parts.scm script into the geda install directory 
share/gEDA/gafrc.d/
Additionally you have to fix the path to the python gedaparts script.

When you open gschem you should see the new libraries and the part lists in the component browser.

Regards
Werner

**Comment by asomers** [comment]
I thought I might be doing something dumb.  The latest commit in my branch automatically includes geda-parts.scm when gnetlist is invoked.  That way, you can do the tests without modifying your geda installation.  You still have to change the paths in geda-parts.scm, though.

**Comment by werner2101** [comment]
Great.

I've pull your code and pushed it to my repo.
Great work.

I'm closing the ticket.

Regards
Werner
