### ISSUE TITLE
Patch of BCP68 fails

### ISSUE THREAD

**Issue by Mike-J-1** [werner2101/spicelib#10]
I ran scons download without issue.  scons create had an error when patching the BCP68 device.

patch -d model_library/nxp/bipolar -p1 < model_patches/BCP68.patch
patching file BCP68.prm
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file BCP68.prm.rej
scons: **\* [model_library/nxp/bipolar/BCP68.prm] Error 1
scons: building terminated because of errors.

Can you help?
Mike

The contents of BCP68.prm.rej is listed here:

--- BCP68.prm   2009-09-26 19:07:42.000000000 -0600
+++ BCP68.prm   2009-09-26 19:10:37.000000000 -0600
@@ -1,16 +1,17 @@
 *

-.SUBCKT BCP68 1 2 3 4

+.SUBCKT BCP68 1 2 3

+*.SUBCKT BCP68 1 2 3 4
- 

-Q1 2 1 3 BCP68 

+Q1 2 1 3 BCP68_model 

 D1 1 2 Diode

-R1 2 4 1f

+*R1 2 4 1f

 *

 *The diode does not reflect a 

 *physical device but improves 

 *only modeling in the reverse 

 *mode of operation.

 *

-.MODEL BCP68 NPN 

+.MODEL BCP68_model NPN 
- IS = 2.312E-013 
- NF = 0.988 
- ISE = 8.851E-014

**Comment by werner2101** [comment]
Hi Mike,

NXP has changed many of their model files.
They've fixed the BCP68 model. The patch is not needed any longer.

I've fixed the issue with commit 36252148877c130616d7

Many other NXP models will fail now. The nxp_bipolar.index file needs some love now.

Regards
Werner
