### ISSUE TITLE
"scoms create" does not populate model_library

### ISSUE THREAD

**Issue by stonux** [werner2101/spicelib#11]
"scoms download" does its job fine. The "downloads" directory gets populated as expected.
I do not know what "scoms create" is supposed to do, I guess populating the "model_library" directory.
"scoms test" fails because "model_library" is not populated.

Is there any manual work to be done to populate the "model_library" directory?
Vendor subdirs and "opamp" subdirs are there, but no files.

Thanks for any help on this.

stonux

**Comment by werner2101** [comment]
Mmmmhhh.

There is an additional step. I thought we made it obsolete.

  scons unpack

to unpack the downloaded zip files of the vendors.

Regards Werner
