### ISSUE TITLE
Spicelib needs a license

### ISSUE THREAD

**Issue by asomers** [werner2101/spicelib#2]
I think we should choose a license for spicelib.  I have just copied some code from pylab, whose license is very permissive and is GPL-compatible.  I have also copied ltcsplit.py, which is GPL-2.  But ltcsplit.py is my own code and I can relicense it however I choose.

My opinion is that spicelib should have a permissive license.  Since it only exists to support the FOSS simulators ngspice and gnucap, there isn't any danger of someone selling a closed source version.  Then again, I suppose it's possible that someone would distribute spicelib, ngspice, and some schematic tool in a bundle.  If that is a danger, then we should use a copyleft license.  

What do you think?

**Comment by werner2101** [comment]
[just added my comment to the tracker]
I'm with you that spicelib should have a permissive licence. Maybe BSD-like.

Well, adding support for other simulator isn't that hard. The main work will be in the mapping definitions between model and symbol (the indexfiles). I think that work could be useful for others, too.
Maybe even for the vendors of the models.

Currently, I've no clear opinion.
