### ISSUE TITLE
Need variable supply voltage for opamp tests

### ISSUE THREAD

**Issue by asomers** [werner2101/spicelib#3]
The current opamp test runs every opamp with a 5V single-sided power supply.  However, many parts in the library require a greater supply.  No one supply voltage will be suitable for testing all amplifiers.  The index file should store information about supply voltage range which should be incorporated into dc_amplifier.sch and/or simulate.ngspice at run time.

**Comment by werner2101** [comment]
[I've already answered that, but can't find my message
here's what I guess I wrote]

I've noticed the same problems when testing the TI opamps.
The easiest thing is to add an additional variable to the index file.

The variable name should be prefixed with "test_". If you need two voltages, positive and negative, then just add two variables.

**Comment by asomers** [comment]
This is fixed in ed94dd54119ca263a5994cf8d0a88371f429bfe7 .  Defined the variable test_vsupply in the index file.  If it is undefined, it will default to 5V.

**Comment by werner2101** [comment]
Thanks.
