### ISSUE TITLE
OPA2652 and other ti opamps fail their tests

### ISSUE THREAD

**Issue by asomers** [werner2101/spicelib#5]
Several opamps, including OPA2652, are marked as model_status=good but fail to simulate on my machine.  In my master branch, they give errors such as :
    Error on line 67 : g.x1.g10 in 0 POLY( 2 ) x1.22 0 x1.23 0 300n 1m 1m
    unknown parameter (x1.22) 
and fail to produce the output file.

In spicelib-0.0.3, OPA2652 does produce the output file, but it is clearly wrong; the output voltage is always 0.

Does OPA2652 simulate correctly on your machine or is it incorrectly marked in ti_opamps.index ?

**Comment by werner2101** [comment]
Works for me.
Which ngspice simulator are you using?
I'm using the ngspice 18 compiled with the following options:

--with-readline=yes --enable-xspice

Maybe the POLY code is in xspice.

**Comment by werner2101** [comment]
I have one opamp that is marked as good, but fails: OPA846_TI00134

## The errror messages are:

testlibrary.pyc running simulation:  cd model_tests/ti/opamps/OPA846_TI00134 ; ngspice -b ../../../../testcircuits/opamp/simulate.ngspice
Warning: singular matrix:  check nodes x1.pnp8 and x1.pnp8
Warning: singular matrix:  check nodes x1.pnp8 and x1.pnp8
Note: starting dynamic Gmin stepping

## Trying gmin =   1.0000E-03 Note: One successful Gmin step

**Comment by asomers** [comment]
I will try recompling ngspice with those options.  That must be it.

**Comment by asomers** [comment]
That did it.  No more errors about POLY

**Comment by werner2101** [comment]
great.
