### ISSUE TITLE
Unable to download national opamps models.

### ISSUE THREAD

**Issue by bert** [werner2101/spicelib#7]
Hi Werner,

See the trail of the build log of a fresh git-clone this afternoon.

--8<--

--2010-05-31 16:17:07--  http://www.national.com/models/spice/LP/LPV324.MOD
Resolving 

www.national.com... 88.221.83.107
Connecting to www.national.com|88.221.83.107|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3794 

(3.7K) [text/plain]
Saving to: “LPV324.MOD”

 0% [                                                        ] 0           --.-K/s              

100%[=======================================================>] 3,794       --.-K/s   in 0.001s  

2010-05-31 16:17:07 (3.21 MB/s) - “LPV324.MOD” saved [3794/3794]

--2010-05-31 16:17:07--  http://www.national.com/models/spice/LP/LPV358.MOD
Resolving www.national.com... 88.221.83.107
Connecting to www.national.com|88.221.83.107|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3794 (3.7K) [text/plain]
Saving to: “LPV358.MOD”

 0% [                                                        ] 0           --.-K/s              

100%[=======================================================>] 3,794       --.-K/s   in 0.003s  

2010-05-31 16:17:07 (1.39 MB/s) - “LPV358.MOD” saved [3794/3794]

--2010-05-31 16:17:07--  ftp://javascript/
           => “.listing”
Resolving javascript... failed: Name or service not known.
wget: unable to resolve host address “javascript”
--2010-05-31 16:17:07--  http://pagetracker._trackpageview('/analog/amplifiers/events/MOD/LPV511');
Resolving pagetracker._trackpageview('... failed: Name or service not known.
wget: unable to resolve host address “pagetracker._trackpageview('”
make: **\* [downloads/national/opamps/spice_models] Error 4

--8<--

I have not dug into this yet.

Kind regards,

Bert Timmerman.

**Comment by werner2101** [comment]
Hi Bert,

I've tried it, but I can not reproduce this error.
I've run the target "scons download_national" and it worked fine.

Maybe it was just an html error at the national homepage.

Regards
Werner

**Comment by bert** [comment]
Hi Werner,
I can't reproduce this anymore on my laptop with Fedora 13 either, maybe the "html" error has gone.
Now problems arise further down the process.
Kind regards,  Bert Timmerman.
