### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by mogliii** [werner2101/spicelib#8]
This was also posted to help-gnucap mailing list

Spicelib fails to build. This is what I did:
1) $ git clone http://github.com/werner2101/spicelib.git
2) $ make all         (in spicelib folder)
... downloading from nxp, ti, national...
... unpacking ...
3) Error message:

> > ...
> > Fixed file "model_library/nxp/bipolar/2PB709ART.prm"
> > scripts/replace_string.py "1 BCX56 NPN" "1 BCX56" model_library/nxp/bipolar/BCX56.prm
> >   ERROR: searchstring not found "1 BCX56 NPN"
> > make: **\* [create_nxp_bipolar] Error 255
> > $
> > <<

I have the following files (among others) in model_library/nxp/bipolar
BCX56_10.prm
BCX56_16.prm
BCX56.prm

The BCX56.prm looks the following:

> > *
> > .SUBCKT BCX56 1 2 3
> > *
> > ---
> > 
> > *
> > - NXP Semiconductors
> >   *
> > - Medium power NPN transistor
> > - Ic= max 1A
> > - Vceo= max 80V
> > - hFE= 63 - 250 @VCE = 2 V; IC = 150 mA
> >   *
> > - Extraction date (week/year): 37/2009
> > - Simulator: Spice 3
> >   *
> > - TOPVIEW:
> >   *
> > -          C
> > -          |
> > -     _____4_____
> > -    |           |
> > -    |           |  SOT89
> > -    |           |
> > -    |___________|
> > -       3  2  1
> > -       |  |  |
> > -       B  C  E
> >   *
> > - Diode D1 is dedicated to improve modeling in reverse
> > - mode of operation and does not reflect a physical device.
> >   *
> >   **********************************************************
> >   *
> >   Q1 2 3 1 MAIN
> >   D1 3 2 DIODE
> >   *
> >   .MODEL MAIN NPN
> > - IS = 7.905E-014
> > - NF = 0.9948
> > - ISE = 6.507E-015
> > - NE = 1.302
> > - BF = 143
> > - IKF = 0.45
> > - VAF = 8
> > - NR = 0.9943
> > - ISC = 2.266E-014
> > - NC = 1.361
> > - BR = 35.83
> > - IKR = 1.8
> > - VAR = 81
> > - RB = 10.4
> > - IRB = 0.0011
> > - RBM = 2.5
> > - RE = 0.0864
> > - RC = 0.1173
> > - XTB = 0
> > - EG = 1.11
> > - XTI = 3
> > - CJE = 1.442E-010
> > - VJE = 0.7013
> > - MJE = 0.3245
> > - TF = 7.8E-010
> > - XTF = 7
> > - VTF = 5
> > - ITF = 2
> > - PTF = 0
> > - CJC = 2.052E-011
> > - VJC = 0.5
> > - MJC = 0.4015
> > - XCJC = 1
> > - TR = 2.3E-008
> > - CJS = 0
> > - VJS = 0.75
> > - MJS = 0.333
> > - FC = 0.9
> >   .MODEL DIODE D
> > - IS = 1.323E-014
> > - N = 0.9814
> > - BV = 1000
> > - IBV = 0.001
> > - RS = 3185
> > - CJO = 0
> > - VJ = 1
> > - M = 0.5
> > - FC = 0
> > - TT = 0
> > - EG = 1.11
> > - XTI = 3
> >   .ENDS
> >   <<

**Comment by werner2101** [comment]
Hi mogliii,

we are no longer using make to build and test the models.
We switched to scons which is more powerfull. The Makefile is outdated.

The commands you should use are the same:
-  scons download
  or scons download_[vendor]
-  scons create
  or scons create_[vendor]
-  scons test
  or scons test_[vendor]_[libraryname]

I think we should update the docs and remove the Makefile.

Regards
Werner
PS: your post on help-gnucap was much shorter ;-)

**Comment by werner2101** [comment]
fixed by fmaker

Thanks a lot
